language: r
warnings_are_errors: true

r_github_packages:
  - hadley/devtools
  - jimhester/covr
  - jimhester/lintr

after_success:
  - source shim_package.sh
  - Rscript -e 'devtools::install()'
  - Rscript -e 'library(covr);coveralls()'
