language: r
sudo: required
warnings_are_errors: false
env: _R_CHECK_CRAN_INCOMING_=FALSE

r_binary_packages:
  - igraph
  - jsonlite
  - devtools
  - httr
  - shiny
  - digest
  - stringdist

r_github_packages:
  - jimhester/robustr
  - jimhester/covr
  - jimhester/lintr
  - hadley/testthat
  - kevinushey/rex

after_success:
  - source shim_package.sh
  - Rscript -e 'devtools::install()'
  - Rscript -e 'library(covr);coveralls()'
