language: r
warnings_are_errors: false
env: _R_CHECK_CRAN_INCOMING_=FALSE

r_binary_packages:
  - igraph
  - jsonlite
  - devtools
  - httr
  - testthat
  - shiny
  - digest
  - stringdist

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - source shim_package.sh
  - Rscript -e 'devtools::install()'
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - cat covr.Rcheck/tests/testthat.Rout.fail
  - cat covr.Rcheck/tests/testthat/*Rout
